### ISSUE TITLE
Question: why yaml?

### ISSUE THREAD

**Issue by leothelocust** [vlocityinc/newport-design-system#32]
Out of curiosity, why YAML? When SASS already supports variables, why add the extra layer of complexity?  Sorry if i'm missing something, but as a UI designer, this just makes the whole s/find/replace process more difficult.

Thanks in advance,
Levi

**Comment by mattgoldspink** [comment]
Hi Levi - great question :)

Newport is a forked from lightning design system for our starting point, which comes with a lot of Salesforce specific features, for example their own custom preview tool, and of course... yaml for defining design tokens. They use yaml because they generate styles/tokens for Aura, CSS, iOS and Android. We just do css. We've been working to tidy up and remove the features of SLDS we don't need over the last 6 months so what you'll see in the latest branch #ins-106.0 is a new previewer built on the open source Storybook tool AND, more importantly, the removal of YAML design tokens and the switch to SCSS variables. I'd suggest checking out that branch so you can see the latest.

I'll close this issue, but feel free to ask any follow up questions.

**Comment by leothelocust** [comment]
Thanks for the info Matt, that's great to hear!  Is #ins-106.0 stable enough to use? or are you just suggesting to check it out to get a feel for it?

Thanks again!

**Comment by mattgoldspink** [comment]
It is stable, but it's not officially released yet. It's being developed in parallel with our upcoming fall release, so for now I'd suggest just checking it out to see if you have any feedback.
